name: Release

on:
  push:
    branches: [ main, master ]

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    # Cache disabled since this is a library without dependencies

    - name: Run tests
      run: |
        go mod download
        go test -v -race ./...

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      with:
        semantic_version: 22
        extra_plugins: |
          @semantic-release/changelog@6.0.3
          @semantic-release/git@10.0.1
          conventional-changelog-conventionalcommits@7.0.2
        branches: |
          [
            'main',
            'master'
          ]
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# No binary release needed for library